[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${MAINNET_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${SEPOLIA_API_KEY}"
arbitrum_one = "https://arb-mainnet.g.alchemy.com/v2/${ARBITRUM_ONE_API_KEY}"
arbitrum_one_sepolia = "https://arb-sepolia.g.alchemy.com/v2/${ARBITRUM_ONE_SEPOLIA_API_KEY}"

[etherscan]
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}", chain = 1 }
sepolia = { key = "${SEPOLIA_ETHERSCAN_API_KEY}", chain = 11155111 }
arbitrum_one = { key = "${ARBITRUM_ONE_ETHERSCAN_API_KEY}", chain = 42161 }
arbitrum_one_sepolia = { key = "${ARBITRUM_ONE_SEPOLIA_ETHERSCAN_API_KEY}", chain = 421614 }